### ISSUE TITLE
Not working with Vue 3 Cli TS

### ISSUE THREAD

**Issue by moshetanzer** [meloalright/vue3-progress#6]
Cannot find module 'vue3-progress' or its corresponding type declarations.ts(2307)

Please help!

**Comment by meloalright** [comment]
Great PR https://github.com/tangyouge/vue3-progress/pull/7

**Comment by meloalright** [comment]
Had published https://www.npmjs.com/package/vue3-progress/v/0.0.1-beta4

**Comment by moshetanzer** [comment]
Amazing! Nice. This is a great component. Happy that was able to make it TS compatible for all to enjoy! Keep up the good work!
